[package]
name = "rvmti"
version = "0.1.0"
authors = ["rel-eng <rel-eng@yandex.ru>"]
license = "BSD-3-Clause"
license-file = "LICENSE"
edition = "2018"

[dependencies]
lazy_static = "1.1.0"
log = "0.4.5"
env_logger = "0.5.13"
failure = "0.1.2"
failure_derive = "0.1.2"
backtrace = "0.3.9"
nix = "0.11.0"
libc = "0.2.43"
byteorder = "1.2.6"
rand = "0.5.5"
chrono = "0.4.6"

[dependencies.rvmti-sys]
path = "rvmti-sys"
version = "0.1.0"

[lib]
name = "rvmti"
crate-type = ["cdylib"]

[profile.dev]
panic = 'unwind'

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = "fat"
debug-assertions = false
codegen-units = 1
panic = 'unwind'
