[package]
name = "rvmti"
version = "0.1.0"
authors = ["rel-eng <rel-eng@yandex.ru>"]
license = "BSD-3-Clause"
license-file = "LICENSE"

[dependencies]
lazy_static = "1.0.0"
log = "0.4.1"
env_logger = "0.5.5"
failure = "0.1.1"
failure_derive = "0.1.1"
backtrace = "0.3.5"
nix = "0.10.0"
libc = "0.2.39"
byteorder = "1.2.1"
rand = "0.4.2"
time = "0.1.39"

[dependencies.rvmti-sys]
path = "rvmti-sys"
version = "0.1.0"

[lib]
name = "rvmti"
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'unwind'
