[package]
authors = ["rel-eng <rel-eng@yandex.ru>"]
build = "build.rs"
description = "Low-level bindings"
include = ["build.rs", "src/**/*", "Cargo.toml"]
license = "BSD-3-Clause"
license-file = "LICENSE"
name = "rvmti-sys"
version = "0.1.0"

[build-dependencies]
bindgen = "0.32.1"
gcc = "0.3.54"
log = "0.3.8"
env_logger = "0.4.3"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'unwind'
